import {
  EyeIcon,
  FireIcon,
  LogoutIcon,
  PencilIcon,
  TrashIcon,
  UserCircleIcon,
  UsersIcon,
} from '@heroicons/react/solid'

// Demo Students for Data Table
export const demoStudents = [
  {
    name: 'Sahin Alom',
    class: '8',
    roll: '1',
    section: 'a',
    email: 'sahin@gmail.com',
    avatar: '',
    bloodGroup: 'a+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'jurbaria',
  },
  {
    name: 'Sajibul Alom',
    class: '9',
    roll: '1',
    section: 'b',
    email: 'sahin@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'b+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'kusmail',
  },
  {
    name: 'Mohosin Alom',
    class: '10',
    roll: '4',
    section: 'c',
    email: 'mohosin@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'ab+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Damor',
  },
  {
    name: 'Humayun Alom',
    class: '11',
    roll: '4',
    section: 'd',
    email: 'humayun@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'o+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Damor',
  },
  {
    name: 'Masum Alom',
    class: '12',
    roll: '2',
    section: 'a',
    email: 'masum@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'o-',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Uttor Jurbaria',
  },
  {
    name: 'Rabius Sani',
    class: '8',
    roll: '3',
    section: 'b',
    email: 'sani@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'b-',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Uttor Jurbaria',
  },
  {
    name: 'Rabius Sajjad',
    class: '9',
    roll: '4',
    section: 'c',
    email: 'sajjad@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'ab-',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Echail',
  },
  {
    name: 'Sinan Alom',
    class: '10',
    roll: '5',
    section: 'd',
    email: 'sinan@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'a-',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Fulbaria Thana Para',
  },
  {
    name: 'Sanjid Alam',
    class: '11',
    roll: '6',
    section: 'a',
    email: 'sanjid@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'a+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Fulbaria Thana Para',
  },
  {
    name: 'Hafizul Hayder',
    class: '12',
    roll: '3',
    section: 'b',
    email: 'hafizul@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'ab+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Fulbaria Thana Road',
  },

  {
    name: 'Sahin Alom',
    class: '8',
    roll: '1',
    section: 'a',
    email: 'sahin@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'a+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'jurbaria',
  },
  {
    name: 'Sajibul Alom',
    class: '9',
    roll: '1',
    section: 'b',
    email: 'sahin@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'b+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'kusmail',
  },
  {
    name: 'Mohosin Alom',
    class: '10',
    roll: '4',
    section: 'c',
    email: 'mohosin@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'ab+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Damor',
  },
  {
    name: 'Humayun Alom',
    class: '11',
    roll: '4',
    section: 'd',
    email: 'humayun@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'o+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Damor',
  },
  {
    name: 'Masum Alom',
    class: '12',
    roll: '2',
    section: 'a',
    email: 'masum@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'o-',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Uttor Jurbaria',
  },
  {
    name: 'Rabius Sani',
    class: '8',
    roll: '3',
    section: 'b',
    email: 'sani@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'b-',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Uttor Jurbaria',
  },
  {
    name: 'Rabius Sajjad',
    class: '9',
    roll: '4',
    section: 'c',
    email: 'sajjad@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'ab-',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Echail',
  },
  {
    name: 'Sinan Alom',
    class: '10',
    roll: '5',
    section: 'd',
    email: 'sinan@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'a-',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Fulbaria Thana Para',
  },
  {
    name: 'Sanjid Alam',
    class: '11',
    roll: '6',
    section: 'a',
    email: 'sanjid@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'a+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Fulbaria Thana Para',
  },
  {
    name: 'Hafizul Hayder',
    class: '12',
    roll: '3',
    section: 'b',
    email: 'hafizul@gmail.com',
    avatar:
      'https://cdn.pixabay.com/photo/2014/04/05/11/39/people-316506_1280.jpg',
    bloodGroup: 'ab+',
    studentPhone: '01712341234',
    fathersName: 'Demo Father',
    fathersProfession: 'Thecher',
    mothersName: 'Demo Mother',
    mothersProfession: 'Housewife',
    parentsPhone: '01712341234',
    address: 'Fulbaria Thana Road',
  },
]

// Dashbord Profile Dropdown Data
export const userDropDownData = [
  {
    id: 1,
    title: 'Profile',
    sublink: '/',
    Icon: UserCircleIcon,
  },
  {
    id: 2,
    title: 'Logout',
    sublink: '/',
    Icon: LogoutIcon,
  },
]

// Dashbord Profile Dropdown Data
export const tableAction = [
  {
    id: 1,
    title: 'view',
    sublink: '/',
    Icon: EyeIcon,
  },
  {
    id: 2,
    title: 'edit',
    sublink: '/',
    Icon: PencilIcon,
  },
  {
    id: 3,
    title: 'delete',
    sublink: '/',
    Icon: TrashIcon,
  },
]

export const dashBoardDSidebarLinks = [
  {
    id: 1,
    name: 'Overview',
    sublink: 'overview',
    Icon: FireIcon,
    active: false,
    nasted: false,
    subCategory: [],
  },
  {
    id: 2,
    name: 'Manage Students',
    sublink: '',
    Icon: UsersIcon,
    active: false,
    nasted: true,
    subCategory: [
      { name: 'All Students', sublink: 'all_students' },
      { name: 'Add New Student', sublink: 'add_student' },
    ],
  },
]
